./
    src/
        extractor.js
        EXTRACTION_SCRIPT.js
        TARGET_URLS.js
    package.json
    package-lock.json
    dist 
        all-channels.json
    output
        elahmad-channels-YYYY-MM-DD.json